@startuml
node "Clients" {
}
node "Load Balancer" {
}
node "API Servers" {
}
node "Timeline Service" {
}
node "Storage (Tweets DB)" {
}
node "Cache (Redis)" {
}
Clients --> LoadBalancer
LoadBalancer --> "API Servers"
"API Servers" --> "Timeline Service"
"Timeline Service" --> "Cache (Redis)"
"Timeline Service" --> "Storage (Tweets DB)"
@enduml
